src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Timestampable;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Name;

    #[ORM\Column(type: 'float')]
    private $price;

    #[ORM\Column(type: 'integer')]
    private $stock;

    #[ORM\Column(type: 'text')]
    private $descriptions;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[ORM\ManyToOne(targetEntity: Category::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(referencedColumnName: 'id',nullable: false)]
    private $category;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $createdAt;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updateAt;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image2;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image3;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image4;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image5;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getDescriptions(): ?string
    {
        return $this->descriptions;
    }

    public function setDescriptions(string $descriptions): self
    {
        $this->descriptions = $descriptions;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function updatedTimestamps(): void
    {
        $dateTimeNow = new \DateTime('now');

        $this->setUpdatedAt($dateTimeNow);

        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }
    public function getCreatedAt() :?\DateTime{
        return $this->createdAt();
    }
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    public function getUpdatedAt() :?\DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getImage2(): ?string
    {
        return $this->image2;
    }

    public function setImage2(?string $image2): self
    {
        $this->image2 = $image2;

        return $this;
    }

    public function getImage3(): ?string
    {
        return $this->image3;
    }

    public function setImage3(?string $image3): self
    {
        $this->image3 = $image3;

        return $this;
    }

    public function getImage4(): ?string
    {
        return $this->image4;
    }

    public function setImage4(?string $image4): self
    {
        $this->image4 = $image4;

        return $this;
    }

    public function getImage5(): ?string
    {
        return $this->image5;
    }

    public function setImage5(?string $image5): self
    {
        $this->image5 = $image5;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %} | {{ app_name }}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
        <link rel="stylesheet" href=" {{ asset('/styles/styles.css') }}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
    <nav class="nav">
        <div class="container">
            <div class="logo">
                <a href="{{ path('main') }}"><img src="{{ asset('/static/code-logos.jpeg') }}" width="100px" alt=""></a>
            </div>
            <div id="mainListDiv" class="main_list">
                <ul class="navlinks">
                    {% if is_granted('ROLE_ADMIN') %}
                        <li><a href="{{ path('app_admin') }}">Admin panel</a></li>
                    {% endif %}
                    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                        <li><a href="{{ path('app_logout') }}">Logout</a></li>
                        {% else %}
                            <li><a href="{{ path('app_login') }}">Log In</a></li>
                            <li><a href="{{ path('app_register') }}">Sing up</a></li>
                    {% endif %}

                </ul>
            </div>
            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
    </nav>
        <div class="main">

            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ label }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}

            {% block body %}

            {% endblock %}
        </div>


    <footer class="text-center text-white  base-footer">
        <!-- Grid container -->
        <div class="container p-4"></div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3 base-footer">
            © 2020 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>



    </body>
</html>

templates/category.html.twig
{% extends 'base.html.twig' %}
{% block title %}  {% endblock %}
{% block body %}
    <p class="text-white text-center">{{ items|length }} items in this category</p>
    <div class="container">
        <div class="row">
            {% for item in items %}
                {% if item.stock > 0 %}
                    <div class="col-3 category-box text-center item-box">
                        <a class="text-white" href="{{ path('product', {'id': item.id}) }}">
                            <img src="{{ asset('/uploads/') }}{{ item.image }}" width="250px" alt="category-image">
                            <p>{{ item.name }}</p>
                            <p>{{ item.price }} $</p>
                        </a>
                    </div>
                {% endif %}

            {% endfor %}
        </div>


    </div>


{% endblock %}

templates/contact.html.twig
{% extends 'base.html.twig' %}
{% block title %} Contact {% endblock %}
{% block body %}

{% endblock %}

templates/main.html.twig
{% extends 'base.html.twig' %}
{% block title %}Home{% endblock %}
{% block body %}
    <div class="main-search">
        <form action="">
            <input type="text" placeholder="Find what you want...">
        </form>
    </div>
    <hr>
    <div class="container">
        <p class="text-center display-4 text-white mb-5">Categories</p>
        <div class="row">
            {% for category in categories %}
                <div class="col-3 category-box text-center">
                    <a class="text-white" href="{{ path('category', {'id': category.id}) }}">
                        <img src="{{ category.image }}" alt="category-image">
                        <p>{{ category.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
        <hr class="text-white p-1">
        <p class="text-left display-5 text-white mb-5">New products</p>
        <div class="row">
            {% for new in new_products %}
                <div class="col-3 category-box text-center">
                    <a class="text-white" href="{{ path('product', {'id': new.id}) }}">
                        <img src="{{ asset('/uploads/') }}{{ new.image }}" alt="category-image">
                        <p>{{ new.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>

    </div>



{% endblock %}

templates/product.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ item.name }}{% endblock %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-4">
                <img class="p-3" src="{{ asset('/uploads/') }}{{ item.image }}" width="400px" alt="main-image">
            </div>
            <div class="col-6 text-white text-left">
                <h1>{{ item.name }}</h1>
                <p>{{ item.descriptions }}</p>
                <h3>{{ item.price }} $</h3>
                <p>Stock {{ item.stock }}</p>
                <button class="btn btn-success">Buy</button>
                <hr>
            </div>

            {% if item.image2 != NULL %}
                <img src="{{ asset('/uploads/') }}{{ item.image2 }}" alt="product-image">
            {% endif %}
            {% if item.image3 != NULL %}
                <img src="{{ asset('/uploads/') }}{{ item.image3 }}" alt="product-image">
            {% endif %}
            {% if item.image4 != NULL %}
                <img src="{{ asset('/uploads/') }}{{ item.image4 }}" alt="product-image">
            {% endif %}
            {% if item.image5 != NULL %}
                <img src="{{ asset('/uploads/') }}{{ item.image5 }}" alt="product-image">
            {% endif %}

        </div>
    </div>

{% endblock %}